import {
     AnimationTwoTone,
     AutoFixHighTwoTone,
     CampaignTwoTone,
     ContentCutTwoTone,
     DrawTwoTone,
     LanguageTwoTone,
     LocalSeeTwoTone,
     MovieFilterTwoTone,
     MusicNoteTwoTone,
     StayCurrentPortraitTwoTone,
     StickyNote2TwoTone,
     SupportAgentTwoTone,
     TheaterComedyTwoTone,
     TipsAndUpdatesTwoTone,
     VideocamTwoTone,
     ViewInArTwoTone,
} from "@mui/icons-material";
import React from "react";
export const servicesData = [
     {
          id: 0,
          title: "Film Making",
          icon: <MovieFilterTwoTone />,
          color: "#f44336",
          text: "",
     },
     {
          id: 1,
          title: "Cinematography",
          icon: <VideocamTwoTone />,
          color: "#ff9800",
          text: "",
     },
     {
          id: 2,
          title: "Directing",
          icon: <TheaterComedyTwoTone />,
          color: "#4caf50",
          text: "",
     },
     {
          id: 3,
          title: "Editing",
          icon: <ContentCutTwoTone />,
          color: "#2196f3",
          text: "",
     },
     {
          id: 4,
          title: "VFX / CGI",
          icon: <ViewInArTwoTone />,
          color: "#9c27b0",
          text: "",
     },
     {
          id: 5,
          title: "Animations",
          icon: <AnimationTwoTone />,
          color: "#e91e63",
          text: "",
     },
     {
          id: 6,
          title: "Photography",
          icon: <LocalSeeTwoTone />,
          color: "#ff5722",
          text: "",
     },
     {
          id: 7,
          title: "Graphics Design",
          icon: <DrawTwoTone />,
          color: "#607d8b",
          text: "",
     },
     {
          id: 8,
          title: "Music / Sounds",
          icon: <MusicNoteTwoTone />,
          color: "#795548",
          text: "",
     },
     {
          id: 9,
          title: "Digital Marketing",
          icon: <CampaignTwoTone />,
          color: "#3f51b5",
          text: "",
     },
     {
          id: 10,
          title: "Website Development",
          icon: <LanguageTwoTone />,
          color: "#009688",
          text: "",
     },
     {
          id: 11,
          title: "App Development",
          icon: <StayCurrentPortraitTwoTone />,
          color: "#8bc34a",
          text: "",
     },
     {
          id: 12,
          title: "Content Writing",
          icon: <StickyNote2TwoTone />,
          color: "#ffeb3b",
          text: "",
     },
     {
          id: 13,
          title: "Tech Support",
          icon: <SupportAgentTwoTone />,
          color: "#ff9800",
          text: "",
     },
     {
          id: 14,
          title: "Brand Building",
          icon: <TipsAndUpdatesTwoTone />,
          color: "#ff5722",
          text: "",
     },
     {
          id: 15,
          title: "Visual Art",
          icon: <AutoFixHighTwoTone />,
          color: "#607d8b",
          text: "",
     },
];
