import "./globals.css";
import { Poppins } from "next/font/google";
import NavbarComponent from "@/Components/NavbarComponent";
import Footer from "@/Components/Footer";
import Providers from "@/Components/Providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata = {
  title: "GRAVITY FILMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="flex flex-col min-h-screen">
        <Providers>
          <NavbarComponent />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
