/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 appring.gltf --transform 
Files: appring.gltf [1.52KB] > appring-transformed.glb [19.56KB] (-1187%)
*/

import React, { useRef } from "react";
import { useCubeTexture, useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Appring(props) {
	const ref = useRef();
	const { nodes, materials } = useGLTF("/appring-transformed.glb");
	useFrame((state, delta) => (ref.current.rotation.y += 0.01));
	useFrame((state, delta) => (ref.current.rotation.x = 1.5708));

	const texture = useCubeTexture(
		["px.png", "nx.png", "py.png", "ny.png", "pz.png", "nz.png"],
		{ path: "/" }
	);
	return (
		<group {...props} scale={1.9} ref={ref} dispose={null}>
			<mesh geometry={nodes.APPRING.geometry} material={materials.Material}>
				<meshStandardMaterial envMap={texture} metalness={1} roughness={0.07} />
			</mesh>
		</group>
	);
}

useGLTF.preload("/appring-transformed.glb");
