/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 planet.gltf --transform 
Files: planet.gltf [1.5KB] > planet-transformed.glb [1.39KB] (7%)
*/

import React, { useRef } from "react";
import { useCubeTexture, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Planet(props) {
	const ref = useRef();
	const { nodes, materials } = useGLTF("/gravity-films/planet-transformed.glb");
	useFrame((state, delta) => (ref.current.rotation.x = 1.5708));
	const texture = useCubeTexture(
		["px.png", "nx.png", "py.png", "ny.png", "pz.png", "nz.png"],
		{ path: "/gravity-films/" }
	);
	return (
		<group {...props} scale={1.9} ref={ref} dispose={null}>
			<mesh geometry={nodes.planet.geometry} material={materials.Material}>
				<meshStandardMaterial envMap={texture} metalness={1} roughness={0.07} />
			</mesh>
		</group>
	);
}

useGLTF.preload("/gravity-films/planet-transformed.glb");
