/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Ring.gltf --transform 
Files: Ring.gltf [1.49KB] > Ring-transformed.glb [1.37KB] (8%)
*/

import React, { useRef } from "react";
import { useCubeTexture, useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Ring(props) {
	const ref = useRef();
	const { nodes, materials } = useGLTF("/Ring-transformed.glb");
	useFrame((state, delta) => (ref.current.rotation.z += 0.01));
	useFrame((state, delta) => (ref.current.rotation.y += 0.01));
	useFrame((state, delta) => (ref.current.rotation.x += 0.01));
	const texture = useCubeTexture(
		["px.png", "nx.png", "py.png", "ny.png", "pz.png", "nz.png"],
		{ path: "/" }
	);
	return (
		<group {...props} ref={ref} scale={1.4} dispose={null}>
			<mesh geometry={nodes.Ring.geometry} material={materials.Material}>
				<meshStandardMaterial envMap={texture} metalness={1} roughness={0.07} />
			</mesh>
		</group>
	);
}

useGLTF.preload("/Ring-transformed.glb");
